//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiFincaVirtual.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiFincaVirtual.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address....
        /// </summary>
        internal static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        internal static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must enter a city..
        /// </summary>
        internal static string CityError {
            get {
                return ResourceManager.GetString("CityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal code.
        /// </summary>
        internal static string CodeAnimal {
            get {
                return ResourceManager.GetString("CodeAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a animal code..
        /// </summary>
        internal static string CodeAnimalError {
            get {
                return ResourceManager.GetString("CodeAnimalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a country..
        /// </summary>
        internal static string CoutryError {
            get {
                return ResourceManager.GetString("CoutryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this record.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        internal static string EMailError {
            get {
                return ResourceManager.GetString("EMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        internal static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your email..
        /// </summary>
        internal static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Farm.
        /// </summary>
        internal static string FarmAdd {
            get {
                return ResourceManager.GetString("FarmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date In.
        /// </summary>
        internal static string FarmDateIn {
            get {
                return ResourceManager.GetString("FarmDateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit farm.
        /// </summary>
        internal static string FarmEdit {
            get {
                return ResourceManager.GetString("FarmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a fist name..
        /// </summary>
        internal static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you forgot your password?.
        /// </summary>
        internal static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromGallery.
        /// </summary>
        internal static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams of care used in milking.
        /// </summary>
        internal static string GramsMilking {
            get {
                return ResourceManager.GetString("GramsMilking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you take the picture?.
        /// </summary>
        internal static string ImageSource {
            get {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Available.
        /// </summary>
        internal static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name..
        /// </summary>
        internal static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name....
        /// </summary>
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milking.
        /// </summary>
        internal static string Milking {
            get {
                return ResourceManager.GetString("Milking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Milking.
        /// </summary>
        internal static string MilkingAdd {
            get {
                return ResourceManager.GetString("MilkingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milking Date.
        /// </summary>
        internal static string MilkingDate {
            get {
                return ResourceManager.GetString("MilkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a milking number.
        /// </summary>
        internal static string MilkingError {
            get {
                return ResourceManager.GetString("MilkingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string MilkingLiters {
            get {
                return ResourceManager.GetString("MilkingLiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the liters of milking.
        /// </summary>
        internal static string MilkingLitersError {
            get {
                return ResourceManager.GetString("MilkingLitersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milking Number.
        /// </summary>
        internal static string MilkingNumber {
            get {
                return ResourceManager.GetString("MilkingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The milking number is 1, 2 or 3.
        /// </summary>
        internal static string MilkingValueError {
            get {
                return ResourceManager.GetString("MilkingValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string MilkingWeight {
            get {
                return ResourceManager.GetString("MilkingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the milking weight.
        /// </summary>
        internal static string MilkingWeightError {
            get {
                return ResourceManager.GetString("MilkingWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name..
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new picture.
        /// </summary>
        internal static string NewPicture {
            get {
                return ResourceManager.GetString("NewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet conection..
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milkings information available..
        /// </summary>
        internal static string NoMilkingsMessage {
            get {
                return ResourceManager.GetString("NoMilkingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm..
        /// </summary>
        internal static string PasswordConfirmError {
            get {
                return ResourceManager.GetString("PasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password confirm....
        /// </summary>
        internal static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password. At least 6 characters..
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        internal static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm must be equals..
        /// </summary>
        internal static string PasswordsNoMatch {
            get {
                return ResourceManager.GetString("PasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password..
        /// </summary>
        internal static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone number..
        /// </summary>
        internal static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number....
        /// </summary>
        internal static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was created successfully. Now you can enter with the email and the assigned password..
        /// </summary>
        internal static string RegisterConfirmation {
            get {
                return ResourceManager.GetString("RegisterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password are not valid..
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a state..
        /// </summary>
        internal static string StateError {
            get {
                return ResourceManager.GetString("StateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tour on your internet settings.
        /// </summary>
        internal static string Touroninternet {
            get {
                return ResourceManager.GetString("Touroninternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
