//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiFincaVirtual.Backend.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiFincaVirtual.Backend.Tools.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un macho no se puede registrar como gestante..
        /// </summary>
        internal static string GestanteMacho {
            get {
                return ResourceManager.GetString("GestanteMacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar por que hay ordeños registrados a este animal..
        /// </summary>
        internal static string Mensaje0001 {
            get {
                return ResourceManager.GetString("Mensaje0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede cargar por que hay cerdas gestantes relacionadas a este animal..
        /// </summary>
        internal static string Mensaje0002 {
            get {
                return ResourceManager.GetString("Mensaje0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta opción por que la tiene registrada al menos un lote con un tipo de animal..
        /// </summary>
        internal static string Mensaje0003 {
            get {
                return ResourceManager.GetString("Mensaje0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta opción por que la tiene registrada un lote indicando el tipo de cuido del lote..
        /// </summary>
        internal static string Mensaje0004 {
            get {
                return ResourceManager.GetString("Mensaje0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta opción por que aparece en un registro de comida como tipo de cuido..
        /// </summary>
        internal static string Mensaje0005 {
            get {
                return ResourceManager.GetString("Mensaje0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta opción por que aparece en un registro de inventario como tipo de cuido..
        /// </summary>
        internal static string Mensaje0006 {
            get {
                return ResourceManager.GetString("Mensaje0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta opción por que aparece en un registro de animales indicando el tipo de animal..
        /// </summary>
        internal static string Mensaje0007 {
            get {
                return ResourceManager.GetString("Mensaje0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el lote por que lo tiene relacionado al menos un registro de comidas lote..
        /// </summary>
        internal static string Mensaje0008 {
            get {
                return ResourceManager.GetString("Mensaje0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el registro..
        /// </summary>
        internal static string Mensaje0009 {
            get {
                return ResourceManager.GetString("Mensaje0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede registrar por que tiene una lactancia activa..
        /// </summary>
        internal static string Mensaje0010 {
            get {
                return ResourceManager.GetString("Mensaje0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se ha eliminado satisfactoriamente..
        /// </summary>
        internal static string RegistroEliminado {
            get {
                return ResourceManager.GetString("RegistroEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se ha guardado satifactoriamene..
        /// </summary>
        internal static string RegistroGuardado {
            get {
                return ResourceManager.GetString("RegistroGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se ha modificado satisfactoriamente..
        /// </summary>
        internal static string RegistroModificado {
            get {
                return ResourceManager.GetString("RegistroModificado", resourceCulture);
            }
        }
    }
}
